# Generated by Django 4.1.1 on 2022-09-28 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='createpost',
            name='date',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name='createpost',
            name='picture',
            field=models.ImageField(blank=True, upload_to='my_app/files/posts'),
        ),
    ]
