# Generated by Django 4.1.1 on 2022-09-29 09:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0002_createpost_date_alter_createpost_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpost',
            name='picture',
            field=models.ImageField(default='default.jpg', upload_to='my_app/files/posts'),
        ),
    ]
