# Generated by Django 4.1.1 on 2022-09-29 09:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0003_alter_createpost_picture'),
    ]

    operations = [
        migrations.AlterField(
            model_name='createpost',
            name='picture',
            field=models.ImageField(blank=True, upload_to='my_app/files/posts'),
        ),
    ]
