# Generated by Django 4.1.1 on 2022-10-03 22:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0004_alter_createpost_picture'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='createpost',
            name='date',
        ),
        migrations.AddField(
            model_name='createpost',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2022, 10, 3, 22, 33, 1, 430573, tzinfo=datetime.timezone.utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='createpost',
            name='edited_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='createpost',
            name='picture',
            field=models.ImageField(blank=True, upload_to='posts/'),
        ),
    ]
