# Generated by Django 4.1.1 on 2022-11-01 14:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('my_app', '0006_alter_createpost_created_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='profile_img',
            field=models.ImageField(blank=True, default='profiles/default_teamyy.jpg', upload_to='profiles/'),
        ),
    ]
